Feat/gyocheol/power
ico-d103/ico pull request #46
Opened 2023-07-12 05:33 UTC by gyocheol

* change 보기
* 아직 권한이 주어진다고 해서 기능들은 사용 x

2023-07-12 17:38 UTC, RUNGOAT requested changes

2023-07-12 17:38 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/controller/PowerController.java
> +public class PowerController {
power가 권한 관련인 거 맞죠?
이 부분은 docs에 명시해주면 좋을 것 같아요~~
service나 다른 관련 부분에도 같이 docs 작성~

2023-07-12 17:38 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +            if (job.getEmpowered().contains(power.getId().toString())) {
job.setEmpowerd("") 코드에서 빈 칸으로 만들고 코드가 내려왔으면 굳이 조건 확인을 안해도 되지 않을까요??

만약, 조건 확인이 필요하다고 해도 job.getEmpowerd()은 고정값이니 반복문 외부에서 미리 변수에 할당하는게 오버헤드가 줄어들 것 같아요

2023-07-12 17:38 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +            studentJobRepository.save(job);
반복문 내부에서 여러분 save 쿼리를 날리는 것보다는 StringBuilder를 사용해서 문자열을 생성, 추가한 다음 반복문을 마친 후에 저장하는게 반복적인 쿼리를 날리지 않아 좋을 것 같습니다

2023-07-12 17:38 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +            log.info(student.getEmpowered());
log를 띄우기에 메세지 정보가 빈약해보여요
어떤 method에서 어떤 정보를 보여주는지 명시해주는게 필요할 것 같습니다
Ex) log.info("[updatePower] 학생들의 권한 정보 : {}", student.getEmpowerd());

2023-07-12 17:38 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +            student.setEmpowered(job.getEmpowered());
job.getEmpowerd() 가 반복적으로 사용되니 미리 변수에 할당해서 오버헤드를 줄이는게 더 효율적인 코드 작성일 것 같습니다~

2023-07-12 17:38 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/user/MemberServiceImpl.java
> +    @Transactional
@Transactional 을 추가한 이유가 있을까요??
로직 보면 조회하는 기능만 있어보이는데 readOnly = true 설정을 해주는게 어떨까요

2023-07-13 15:23 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +            if (job.getEmpowered().contains(power.getId().toString())) {
리스트에 중복으로 들어오는 것을 막으려고 작성했습니다. 고정값을 미리 변수에 할당해서 적용했습니다~

2023-07-18 07:42 UTC, RUNGOAT requested changes
확인 후 말씀해주세요~

2023-07-19 09:43 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/controller/PowerController.java
> +public class PowerController {
작성했습니다.

2023-07-19 12:11 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +        Collections.sort(ids);
해당 코드는 
`Set<Long> setPowerIds = new TreeSet<>(powerIds);`
으로 축약해서 더 효율적으로 작성할 수 있습니다.

TreeSet 자료구조에 대해 학습해보시면 좋을 듯 합니다.

TreeSet은 데이터를 저장할 시 이진탐색트리(BinarySearchTree)의 형태로 데이터를 저장해서 자동으로 정렬을 수행합니다.
정렬을 수행한 후 for-each로 전체 조회하기 때문에 List로 변환할 필요도 없습니다.

2023-07-19 12:12 UTC, RUNGOAT approved these changes

2023-07-19 13:03 UTC, merged