자격증 관련
ico-d103/ico pull request #52
Opened 2023-07-19 13:13 UTC by gyocheol

* 수정, 삭제, 생성 시 학생에게 자동 적용
* 학생들의 자격증 등급 조정
* 모든 학생들의 자격증 등급 조정

2023-07-19 14:14 UTC, RUNGOAT requested changes
코멘트 내용 확인해서 반영해주세요

2023-07-19 14:14 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseServiceImpl.java
> +            StudentLicense license = studentLicenseRepository.findById(m.getKey())
인자로 넣기 전에 유효성 검사하셔야 됩니다.
Map을 사용하니 어떤 key를 받는건지, 무슨 key인지 파악이 안되요

2023-07-19 17:52 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/dto/license/LicenseUpdateReqDto.java
> +public class LicenseUpdateReqDto {
설명 달았습니다~

2023-07-19 17:52 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/controller/LicenseController.java
> +    public ResponseEntity<HttpStatus> updateAllStudentLicense(HttpServletRequest request, @RequestBody LicenseUpdateReqDto dto) {
annotation 적용했습니다.

2023-07-19 17:52 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseServiceImpl.java
> +            StudentLicense license = studentLicenseRepository.findById(m.getKey())
고쳐보겠습니다~

2023-07-19 17:55 UTC, gyocheol commented on Back-end/core-module/src/main/java/com/ico/core/entity/StudentLicense.java
> +
참조를 하면 조회할때마다 nationLicense를 들어가서 조회를 하기 때문에 Id만 같이 저장하여 학생 전체 등급을 조정할 때 사용하기 위해 참조를 끊고 id만 저장했습니다.

2023-07-19 17:56 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/nation/NationServiceImpl.java
> +    public void deleteNation(HttpServletRequest request) {  // NationLicense, StudentLicense, power 지워야 함
지금해서 푸쉬하겠습니다!

2023-07-20 13:27 UTC, RUNGOAT approved these changes

2023-07-20 17:50 UTC, merged