Map Dto로 변경 및 지은이가 원하는 타입으로 Map 타입 변경
ico-d103/ico pull request #62
Opened 2023-07-27 10:27 UTC by gyocheol

2023-07-27 16:14 UTC, RUNGOAT requested changes

2023-07-27 16:14 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/controller/LicenseController.java
> +        licenseService.updateStudentLicense(request, map.getLicenses());
변수명 정확하게 작성해주세요
`map`이 아니라 `dto`가 되어야 하지 않을까요?

2023-07-27 16:14 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/controller/LicenseController.java
> +        licenseService.updateStudentDetailLicense(request, studentId, map.getLicenses());
변수명 정확하게 작성해주세요
`map`이 아니라 `dto`가 되어야 하지 않을까요?

2023-07-27 16:14 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseServiceImpl.java
>              if (!nationId.equals(license.getNation().getId())) {
license의 `getNation()`이 반드시 null이 아니라는 것을 보장할 수 있나요?
그렇지 않으면 `getId()`에서 NPE가 발생합니다.

2023-07-27 16:14 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseService.java
> +    void updateStudentLicense(HttpServletRequest request, Map<Long, Integer> map);
매개변수로 Map을 사용한 이유가 있나요?
코드를 처음 보는 입장에서 `map`이 무엇을 의미하는지 알 수가 없습니다.

2023-07-27 16:14 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseServiceImpl.java
> +    public void updateStudentLicense(HttpServletRequest request, Map<Long, Integer> map) {
매개변수로 Map을 사용한 이유가 있나요?
코드를 처음 보는 입장에서 `map`이 무엇을 의미하는지 알 수가 없습니다.

2023-07-27 16:14 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseServiceImpl.java
>              }
사용자에게 예외에 대한 명확한 내용을 전달하는게 좋습니다.
상세하게 분리하여 작성해주길 바랍니다.

2023-07-28 11:46 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseService.java
> +    void updateStudentLicense(HttpServletRequest request, Map<Long, Integer> map);
프론트에서 Map 형태로 보내는 것이 빠르고 편리하다고 해서 Map 형태로 받고 있습니다.

2023-07-28 11:46 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseServiceImpl.java
> +    public void updateStudentLicense(HttpServletRequest request, Map<Long, Integer> map) {
위와 같습니다.

2023-07-28 11:47 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseServiceImpl.java
>              }
네 좋은 의견인 것 같습니다.

2023-07-28 11:47 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseServiceImpl.java
>              if (!nationId.equals(license.getNation().getId())) {
유효성 검사하겠습니다.

2023-07-31 12:53 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseServiceImpl.java
>              if (!nationId.equals(license.getNation().getId())) {
nationLicenseId가 getNation()이랑 연관이 있을까요??
nation에 관해 어디서 유효성 검사를 하고 있나요???

2023-07-31 13:06 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseService.java
> +    void updateStudentLicense(HttpServletRequest request, Map<Long, Integer> map);
프론트가 Map 형태로 보내는 것은 json 형태로 전달하게 됩니다.
서버 측의 Spring Boot 내부에서는 @RequestBody를 통해 json 형태의 데이터를 받아 객체에 매핑하게 됩니다.

그렇기 때문에 프론트가 Map을 보내는 것과는 연관이 없으며 DTO로 받아서 validation 체크를 하고
매개변수 전달은 DTO를 전달하든 id값에 대해서만 전달하든
해당 변수가 무엇을 의미하는지 알 수 있는 가독성을 고려해서 작성해주시길 바랍니다.

2023-07-31 13:14 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/License/LicenseService.java
> +    void updateStudentLicense(HttpServletRequest request, Map<Long, Integer> map);
map이 id값에 대한 어떠한 value 값을 가진다면 해당 내용을 포함하는 변수명을 작성해주고
변수명만으로 설명이 부족하면 주석에 추가 설명을 하는게 어떨까요?

2023-08-02 15:42 UTC, merged