직업 수정 시 권한, 자격증 수정 기능 및 직업에 부여하는 자격증 관련 pr
ico-d103/ico pull request #68
Opened 2023-08-03 11:20 UTC by gyocheol

양이 많습니다.. 천천히 읽어봐주세요~

2023-08-03 22:40 UTC, RUNGOAT requested changes

2023-08-03 22:40 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +                for (JobLicense jobLicense : jobLicenses) {
if 문이 없어도 데이터가 없으면 for문 내부 로직은 실행되지 않습니다.

2023-08-03 22:40 UTC, RUNGOAT commented on Back-end/core-module/src/main/java/com/ico/core/dto/JobReqDto.java
> +        this.salary = wage;
wage 변수명도 수정해야 되지 않나요?

2023-08-03 22:40 UTC, RUNGOAT commented on Back-end/core-module/src/main/java/com/ico/core/entity/JobLicense.java
> +    private NationLicense license;
우리 license 관련 두 테이블이 있는데 변수명을 license라고 하면 무엇을 가리키는지 바로 확인이 어렵습니다.

2023-08-03 22:40 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +            }
예외가 발생할 수 있는 두 가지 경우가 있네요.
이럴 경우 예외를 나눠주는 것이 명확한 메세지를 전달할 수 있겠죠.
만약 이것이 번거롭다면 log를 찍어 두는 건 어떨까요

2023-08-04 09:42 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/controller/JobController.java
> +     * wage > salary
넵 변경했다고 표시해둔 겁니다.

2023-08-04 09:56 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/dto/job/JobAddReqDto.java
> +        this.salary = wage;
Rename 으로 수정했는데 안바꼈네요.. 감사합니다!

2023-08-04 09:57 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/controller/JobLicenseController.java
> +@RequestMapping("api/jobLicense")
넵 수정하겠습니다.

2023-08-04 10:14 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/dto/job/JobLicenseReqDto.java
> +    private Integer rating;
message 가 없어도 
{
    "code": "must be greater than or equal to 0",
    "message": "rating 필드의 입력값[ -1 ]이 유효하지 않습니다."
}
이런 형식으로 반환해서 안보냈습니다.

2023-08-04 10:27 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +                for (JobLicense jobLicense : jobLicenses) {
감사합니다!

2023-08-04 10:29 UTC, gyocheol commented on Back-end/core-module/src/main/java/com/ico/core/dto/JobReqDto.java
> +        this.salary = wage;
Rename 으로 수정했는데 안바꼈네요.. 감사합니다!

2023-08-04 10:32 UTC, gyocheol commented on Back-end/core-module/src/main/java/com/ico/core/entity/JobLicense.java
> +    private NationLicense license;
넵 수정하겠습니다.

2023-08-04 10:39 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobServiceImpl.java
> +            }
넵 log로 rating을 볼 수 있게 하겠습니다.

2023-08-04 11:11 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobLicenseServiceImpl.java
> +        NationLicense nationLicense = nationLicenseRepository.findByNationIdAndId(nationId, dto.getLicenseId())
where
            studentjob0_.id=? 
            and nation1_.id=?
위 방식을 통해 최적화 수행을 하고 있습니다.

2023-08-04 12:20 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobLicenseServiceImpl.java
> +        List<JobLicense> jobLicenses = jobLicenseRepository.findAllById(dto.getJobLicenseIds());
코드 수정했습니다.

2023-08-04 13:09 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/controller/JobController.java
> +     * wage > salary
음 해당 변수들은 int 값이라 대소 비교하는 것으로 헷갈릴 수도 있을 것 같아요
그리고 변수명을 바꿨다면 Pull requests description에 어떤 부분을 전체적으로 바꿨는지 적어주시면 확인하기 좋을 것 같습니다!

2023-08-04 13:22 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobLicenseServiceImpl.java
> +        List<JobLicense> jobLicenses = jobLicenseRepository.findAllById(dto.getJobLicenseIds());
관련 링크 참조한 것 좋습니다.
내용을 살펴보니 for (ID id : ids) 반복문 안에서 findById로 테이블 조회를 하는 군요.
하지만 쿼리문은 in 을 사용해 조회를 하는데 내부적으로 최적화된 쿼리문을 작성하는 건지 추후에 알아보면 좋을 것 같습니다.

2023-08-04 14:41 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/service/job/JobLicenseServiceImpl.java
> +        List<JobLicense> jobLicenses = jobLicenseRepository.findAllById(dto.getJobLicenseIds());
넵 좋습니다.

2023-08-04 14:41 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/controller/JobController.java
> +     * wage > salary
넵 변경해서 푸쉬하겠습니다.

2023-08-04 14:47 UTC, gyocheol commented on Back-end/api-module/src/main/java/com/ico/api/dto/job/JobLicenseReqDto.java
> +    private Integer rating;
size 어노테이션으로 수정했고 min default가 0이라 min은 생략했습니다.

2023-08-04 15:07 UTC, RUNGOAT commented on Back-end/api-module/src/main/java/com/ico/api/dto/job/JobLicenseReqDto.java
> +    private Integer rating;
죄송해요 제가 annotation을 착각했어요
@Size 가 아니라 @Range를 사용해야 합니다.
수정 부탁드립니다..

2023-08-04 15:08 UTC, RUNGOAT approved these changes

2023-08-04 15:30 UTC, merged